#include "rsmicro/rsm_runtime.h"
#include "rsmicro/rsm_opcodes.h"
#include <float.h>
#include <limits.h>
#include <math.h>
#include <string.h>
#define HS 72u
#define DS 20u
#define NONE UINT32_MAX
typedef struct {uint8_t type,storage,retentive,pad; union {rsm_bool_t b;rsm_dint_t d;rsm_real_t f;rsm_timer_t timer;rsm_counter_t counter;} v;} tag_t;
typedef struct {uint8_t enabled; rsm_value_t value;} force_t;
typedef struct {uint8_t edge,valid; uint64_t time;} state_t;
typedef struct {const uint8_t *image,*code;size_t image_size,code_size;uint32_t tags,states,instructions,rungs;tag_t *tag;force_t *force;state_t *state;const uint8_t *rung_data;rsm_runtime_diagnostics_t diag;rsm_fault_t fault;} impl_t;
static uint16_t u16(const uint8_t*p){return (uint16_t)((uint16_t)p[0]|((uint16_t)p[1]<<8));}
static uint32_t u32(const uint8_t*p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static int32_t i32(const uint8_t*p){uint32_t x=u32(p);int32_t v;memcpy(&v,&x,4);return v;}
static uint64_t now(const rsm_runtime_t*r){return r->hal.monotonic_time_us(r->hal_context);}
static uint32_t crc32(const uint8_t*p,size_t n){uint32_t c=UINT32_MAX;size_t i;for(i=0;i<n;i++){unsigned k;c^=p[i];for(k=0;k<8;k++)c=(c>>1)^((0u-(c&1u))&0xedb88320u);}return ~c;}
static rsm_status_t sections(const uint8_t*x,size_t n,uint16_t wanted,const uint8_t **p,size_t *z){uint16_t count,j;if(n<HS)return RSM_STATUS_BAD_IMAGE;count=u16(x+18);if((size_t)HS+(size_t)count*DS>n)return RSM_STATUS_BAD_IMAGE;for(j=0;j<count;j++){const uint8_t*d=x+HS+(size_t)j*DS;uint32_t o=u32(d+4),l=u32(d+8);if((size_t)o>n||(size_t)l>n-(size_t)o)return RSM_STATUS_BAD_IMAGE;if(u16(d)==wanted){*p=x+o;*z=l;return RSM_STATUS_OK;}}return RSM_STATUS_BAD_IMAGE;}
const char *rsm_status_name(rsm_status_t s){static const char *const n[]={"OK","INVALID_ARGUMENT","INVALID_STATE","BUFFER_TOO_SMALL","OUT_OF_MEMORY","BAD_IMAGE","BAD_CRC","UNSUPPORTED_IMAGE_VERSION","UNSUPPORTED_PROFILE","UNSUPPORTED_ABI","UNSUPPORTED_OPCODE","TYPE_MISMATCH","TAG_NOT_FOUND","MEMBER_NOT_FOUND","NOT_WRITABLE","FAULTED","HAL_ERROR","SCAN_OVERRUN","QUEUE_FULL"};return (unsigned)s<sizeof n/sizeof n[0]?n[s]:"UNKNOWN";}
rsm_status_t rsm_runtime_validate_image(const uint8_t*x,size_t n,rsm_image_info_t*out){uint32_t saved;uint8_t tmp[4]={0};uint16_t count,i,j;const uint8_t*p;size_t z;if(!x||!out)return RSM_STATUS_INVALID_ARGUMENT;if(n<HS||memcmp(x,"RSM1",4))return RSM_STATUS_BAD_IMAGE;if(x[4]!=1)return RSM_STATUS_UNSUPPORTED_IMAGE_VERSION;if(u16(x+6)!=HS||u32(x+8)!=n)return RSM_STATUS_BAD_IMAGE;if(u16(x+16)!=1)return RSM_STATUS_UNSUPPORTED_ABI;count=u16(x+18);if(!count||(size_t)count*DS>n-HS)return RSM_STATUS_BAD_IMAGE;for(i=0;i<count;i++){uint32_t o=u32(x+HS+(size_t)i*DS+4),l=u32(x+HS+(size_t)i*DS+8);if(o<HS+(uint32_t)count*DS||(size_t)o>n||(size_t)l>n-o)return RSM_STATUS_BAD_IMAGE;for(j=0;j<i;j++){uint32_t a=u32(x+HS+(size_t)j*DS+4),b=u32(x+HS+(size_t)j*DS+8);if(u16(x+HS+(size_t)i*DS)==u16(x+HS+(size_t)j*DS))return RSM_STATUS_BAD_IMAGE;if(o<a+b&&a<o+l)return RSM_STATUS_BAD_IMAGE;}}
saved=u32(x+68);{uint32_t c=UINT32_MAX;size_t k;for(k=0;k<n;k++){unsigned q;uint8_t b=(k>=68&&k<72)?tmp[k-68]:x[k];c^=b;for(q=0;q<8;q++)c=(c>>1)^((0u-(c&1u))&0xedb88320u);}if(~c!=saved)return RSM_STATUS_BAD_CRC;}if(sections(x,n,15,&p,&z)||z<4||z!=4u+(size_t)u32(p)*20u)return RSM_STATUS_BAD_IMAGE;if(sections(x,n,8,&p,&z))return RSM_STATUS_BAD_IMAGE;{size_t o=0;uint32_t ic=0;while(o<z){uint8_t ac;if(z-o<12)return RSM_STATUS_BAD_IMAGE;ac=p[o+1];if(ac>3||z-o<12u+(size_t)ac*8u)return RSM_STATUS_BAD_IMAGE;if(p[o]==0)return RSM_STATUS_UNSUPPORTED_OPCODE;o+=12u+(size_t)ac*8u;ic++;}out->instruction_count=ic;}out->major=x[4];out->minor=x[5];out->profile_id=u16(x+12);out->instruction_abi=u16(x+16);out->section_count=count;out->image_size=u32(x+8);sections(x,n,15,&p,&z);out->tag_count=u32(p);(void)crc32;return RSM_STATUS_OK;}
rsm_status_t rsm_runtime_required_memory(const uint8_t*x,size_t n,size_t*out){rsm_image_info_t i;rsm_status_t s;if(!out)return RSM_STATUS_INVALID_ARGUMENT;s=rsm_runtime_validate_image(x,n,&i);if(s)return s;*out=sizeof(impl_t)+(size_t)i.tag_count*(sizeof(tag_t)+sizeof(force_t))+(size_t)i.instruction_count*sizeof(state_t)+16u;return RSM_STATUS_OK;}
static uintptr_t align8(uintptr_t p){return (p+7u)&~(uintptr_t)7u;}
rsm_status_t rsm_runtime_init(rsm_runtime_t*r,void*a,size_t z,const rsm_hal_t*h,void*c){if(!r||!a||!h||!h->monotonic_time_us)return RSM_STATUS_INVALID_ARGUMENT;memset(r,0,sizeof *r);r->arena=a;r->arena_size=z;r->hal=*h;r->hal_context=c;r->mode=RSM_MODE_PROGRAM;return RSM_STATUS_OK;}
void rsm_runtime_deinit(rsm_runtime_t*r){if(r){r->impl=NULL;r->mode=RSM_MODE_PROGRAM;}}
rsm_status_t rsm_runtime_load_image(rsm_runtime_t*r,const uint8_t*x,size_t n){rsm_image_info_t in;rsm_status_t s;size_t need,z;const uint8_t*p,*code,*rg;uintptr_t q;uint32_t k;if(!r)return RSM_STATUS_INVALID_ARGUMENT;if(r->mode!=RSM_MODE_PROGRAM)return RSM_STATUS_INVALID_STATE;s=rsm_runtime_validate_image(x,n,&in);if(s)return s;s=rsm_runtime_required_memory(x,n,&need);if(s)return s;if(need>r->arena_size)return RSM_STATUS_BUFFER_TOO_SMALL;sections(x,n,15,&p,&z);sections(x,n,8,&code,&z);q=align8((uintptr_t)r->arena);r->impl=(void*)q;{impl_t*m=r->impl;memset(m,0,sizeof *m);q=align8(q+sizeof *m);m->tag=(tag_t*)q;q=align8(q+(size_t)in.tag_count*sizeof(tag_t));m->force=(force_t*)q;q=align8(q+(size_t)in.tag_count*sizeof(force_t));m->state=(state_t*)q;memset(m->tag,0,(size_t)in.tag_count*sizeof(tag_t));memset(m->force,0,(size_t)in.tag_count*sizeof(force_t));memset(m->state,0,(size_t)in.instruction_count*sizeof(state_t));m->image=x;m->image_size=n;m->tags=in.tag_count;m->states=in.instruction_count;m->instructions=in.instruction_count;m->code=code;sections(x,n,8,&code,&m->code_size);m->code=code;if(sections(x,n,16,&rg,&z)==RSM_STATUS_OK&&z>=4){m->rungs=u32(rg);m->rung_data=rg+4;}for(k=0;k<m->tags;k++){const uint8_t*t=p+4+(size_t)k*20;m->tag[k].type=t[0];m->tag[k].storage=t[1];m->tag[k].retentive=t[2];if(t[0]==1)m->tag[k].v.b=(rsm_bool_t)(u32(t+4)!=0);else if(t[0]==2)m->tag[k].v.d=i32(t+4);else if(t[0]==3)memcpy(&m->tag[k].v.f,t+4,4);else if(t[0]==4){m->tag[k].v.timer.pre=i32(t+4);m->tag[k].v.timer.acc=i32(t+8);}else {m->tag[k].v.counter.pre=i32(t+4);m->tag[k].v.counter.acc=i32(t+8);}}m->diag.tag_count=m->tags;m->diag.instruction_count=m->instructions;}return RSM_STATUS_OK;}
rsm_status_t rsm_runtime_unload_program(rsm_runtime_t*r){if(!r)return RSM_STATUS_INVALID_ARGUMENT;if(r->mode!=RSM_MODE_PROGRAM)return RSM_STATUS_INVALID_STATE;r->impl=NULL;return RSM_STATUS_OK;}
static rsm_status_t value(const impl_t*m,uint32_t id,rsm_value_t*v){const tag_t*t;if(id>=m->tags)return RSM_STATUS_TAG_NOT_FOUND;t=&m->tag[id];v->type=(rsm_data_type_t)t->type;if(t->type==1)v->value.boolean=t->v.b?RSM_TRUE:RSM_FALSE;else if(t->type==2)v->value.dint=t->v.d;else if(t->type==3)v->value.real=t->v.f;else return RSM_STATUS_TYPE_MISMATCH;if(m->force[id].enabled)*v=m->force[id].value;return RSM_STATUS_OK;}
static rsm_status_t put(impl_t*m,uint32_t id,const rsm_value_t*v){tag_t*t;if(id>=m->tags)return RSM_STATUS_TAG_NOT_FOUND;t=&m->tag[id];if(t->storage==1)return RSM_STATUS_NOT_WRITABLE;if((unsigned)v->type!=t->type)return RSM_STATUS_TYPE_MISMATCH;if(t->type==1)t->v.b=v->value.boolean?RSM_TRUE:RSM_FALSE;else if(t->type==2)t->v.d=v->value.dint;else if(t->type==3)t->v.f=v->value.real;else return RSM_STATUS_TYPE_MISMATCH;return RSM_STATUS_OK;}
rsm_status_t rsm_runtime_read_tag(const rsm_runtime_t*r,rsm_tag_id_t id,rsm_value_t*v){if(!r||!r->impl||!v)return RSM_STATUS_INVALID_ARGUMENT;return value(r->impl,id,v);}
rsm_status_t rsm_runtime_write_tag(rsm_runtime_t*r,rsm_tag_id_t id,const rsm_value_t*v){if(!r||!r->impl||!v)return RSM_STATUS_INVALID_ARGUMENT;return put(r->impl,id,v);}
rsm_status_t rsm_runtime_read_member(const rsm_runtime_t*r,rsm_tag_id_t id,rsm_member_id_t member,rsm_value_t*v){impl_t*m;if(!r||!r->impl||!v)return RSM_STATUS_INVALID_ARGUMENT;m=r->impl;if(id>=m->tags)return RSM_STATUS_TAG_NOT_FOUND;if(m->tag[id].type==4){rsm_timer_t*t=&m->tag[id].v.timer;if(member==1||member==2){v->type=RSM_TYPE_DINT;v->value.dint=member==1?t->pre:t->acc;}else if(member>=3&&member<=5){v->type=RSM_TYPE_BOOL;v->value.boolean=member==3?t->en:member==4?t->tt:t->dn;}else return RSM_STATUS_MEMBER_NOT_FOUND;return RSM_STATUS_OK;}if(m->tag[id].type==5){rsm_counter_t*c=&m->tag[id].v.counter;if(member<=2&&member){v->type=RSM_TYPE_DINT;v->value.dint=member==1?c->pre:c->acc;}else if(member>=5&&member<=9){v->type=RSM_TYPE_BOOL;v->value.boolean=member==5?c->dn:member==6?c->cu:member==7?c->cd:member==8?c->ov:c->un;}else return RSM_STATUS_MEMBER_NOT_FOUND;return RSM_STATUS_OK;}return RSM_STATUS_TYPE_MISMATCH;}
rsm_status_t rsm_runtime_force_tag(rsm_runtime_t*r,uint32_t id,const rsm_value_t*v){impl_t*m;if(!r||!r->impl||!v)return RSM_STATUS_INVALID_ARGUMENT;m=r->impl;if(id>=m->tags)return RSM_STATUS_TAG_NOT_FOUND;if((unsigned)v->type!=m->tag[id].type||m->tag[id].type>3)return RSM_STATUS_TYPE_MISMATCH;if(!m->force[id].enabled)m->diag.active_force_count++;m->force[id].enabled=1;m->force[id].value=*v;if(v->type==RSM_TYPE_BOOL)m->force[id].value.value.boolean=v->value.boolean?1u:0u;return RSM_STATUS_OK;}
rsm_status_t rsm_runtime_clear_force(rsm_runtime_t*r,uint32_t id){impl_t*m;if(!r||!r->impl)return RSM_STATUS_INVALID_ARGUMENT;m=r->impl;if(id>=m->tags)return RSM_STATUS_TAG_NOT_FOUND;if(m->force[id].enabled){m->force[id].enabled=0;m->diag.active_force_count--;}return RSM_STATUS_OK;}
rsm_status_t rsm_runtime_clear_all_forces(rsm_runtime_t*r){uint32_t i;impl_t*m;if(!r||!r->impl)return RSM_STATUS_INVALID_ARGUMENT;m=r->impl;for(i=0;i<m->tags;i++)m->force[i].enabled=0;m->diag.active_force_count=0;return RSM_STATUS_OK;}
static rsm_status_t operand(const impl_t*m,const uint8_t*o,rsm_value_t*v){uint8_t kind=o[0],type=o[1],member=o[2];uint32_t x=u32(o+4);if(kind==1){if(member){rsm_runtime_t fake;memset(&fake,0,sizeof fake);fake.impl=(void*)m;return rsm_runtime_read_member(&fake,x,member,v);}return value(m,x,v);}v->type=(rsm_data_type_t)type;if(type==1)v->value.boolean=(rsm_bool_t)(x!=0);else if(type==2)v->value.dint=i32(o+4);else if(type==3)memcpy(&v->value.real,o+4,4);else return RSM_STATUS_TYPE_MISMATCH;return RSM_STATUS_OK;}
static bool numeric(const rsm_value_t*v){return v->type==RSM_TYPE_DINT||v->type==RSM_TYPE_REAL;}
static double number(const rsm_value_t*v){return v->type==RSM_TYPE_DINT?(double)v->value.dint:(double)v->value.real;}
static rsm_status_t fail(rsm_runtime_t*r,rsm_fault_category_t c,uint32_t code,const char*msg,uint32_t iid,uint8_t op,uint32_t tag){impl_t*m=r->impl;m->fault.category=c;m->fault.code=code;m->fault.scan_number=m->diag.scan_count;m->fault.timestamp_us=now(r);m->fault.instruction_id=iid;m->fault.opcode=op;m->fault.tag_id=tag;m->fault.major=1;m->fault.message_id=msg;m->diag.fault_count++;r->mode=RSM_MODE_FAULTED;return RSM_STATUS_FAULTED;}
static rsm_status_t destination(impl_t*m,const uint8_t*o,const rsm_value_t*v){if(o[0]!=1||o[2])return RSM_STATUS_NOT_WRITABLE;return put(m,u32(o+4),v);}
static rsm_status_t execute(rsm_runtime_t*r,const uint8_t*p,bool*power,uint64_t tick){impl_t*m=r->impl;uint8_t op=p[0],ac=p[1];uint32_t iid=u32(p+4);int32_t slot=i32(p+8);const uint8_t*a=p+12,*b=a+8,*d=b+8;rsm_value_t x,y,z;rsm_status_t s;if(ac&&op!=RSM_OP_TON&&op!=RSM_OP_CTU&&op!=RSM_OP_CTD&&op!=RSM_OP_RES&&operand(m,a,&x))return fail(r,RSM_FAULT_EXECUTION,1,"OPERAND",iid,op,u32(a+4));
#define NEED(N) do{if(ac!=(N))return fail(r,RSM_FAULT_EXECUTION,2,"ARITY",iid,op,NONE);}while(0)
 if(op==RSM_OP_XIC||op==RSM_OP_XIO){NEED(1);if(x.type!=RSM_TYPE_BOOL)return fail(r,RSM_FAULT_EXECUTION,3,"TYPE",iid,op,u32(a+4));*power=*power&&((op==RSM_OP_XIC)?x.value.boolean!=0:x.value.boolean==0);}
 else if(op>=RSM_OP_OTE&&op<=RSM_OP_OTU){rsm_value_t q;NEED(1);q.type=RSM_TYPE_BOOL;q.value.boolean=*power?1u:0u;if(op==RSM_OP_OTE)s=destination(m,a,&q);else if(*power){q.value.boolean=(op==RSM_OP_OTL)?1u:0u;s=destination(m,a,&q);}else s=RSM_STATUS_OK;if(s)return fail(r,RSM_FAULT_EXECUTION,4,"WRITE",iid,op,u32(a+4));}
 else if(op==RSM_OP_ONS){NEED(0);if(slot<0||(uint32_t)slot>=m->states)return fail(r,RSM_FAULT_EXECUTION,5,"STATE_SLOT",iid,op,NONE);{bool in=*power;*power=in&&!m->state[slot].edge;m->state[slot].edge=(uint8_t)in;}}
 else if(op==RSM_OP_TON){tag_t*t;NEED(1);if(a[0]!=1||u32(a+4)>=m->tags||(t=&m->tag[u32(a+4)])->type!=4)return fail(r,RSM_FAULT_TIMER,1,"TIMER_TAG",iid,op,u32(a+4));if(slot<0||(uint32_t)slot>=m->states)return fail(r,RSM_FAULT_TIMER,2,"STATE_SLOT",iid,op,u32(a+4));if(t->v.timer.pre<0)return fail(r,RSM_FAULT_TIMER,3,"NEGATIVE_PRE",iid,op,u32(a+4));if(*power){uint64_t delta=0;t->v.timer.en=1;if(m->state[slot].valid)delta=tick-m->state[slot].time;m->state[slot].valid=1;m->state[slot].time=tick;if(delta/1000u>(uint64_t)(INT32_MAX-t->v.timer.acc))t->v.timer.acc=INT32_MAX;else t->v.timer.acc+=(int32_t)(delta/1000u);t->v.timer.dn=(rsm_bool_t)(t->v.timer.acc>=t->v.timer.pre);t->v.timer.tt=(rsm_bool_t)!t->v.timer.dn;}else{t->v.timer.en=t->v.timer.tt=t->v.timer.dn=0;t->v.timer.acc=0;m->state[slot].valid=0;}}
 else if(op==RSM_OP_CTU||op==RSM_OP_CTD){tag_t*t;bool rise;NEED(1);if(a[0]!=1||u32(a+4)>=m->tags||(t=&m->tag[u32(a+4)])->type!=5)return fail(r,RSM_FAULT_COUNTER,1,"COUNTER_TAG",iid,op,u32(a+4));if(slot<0||(uint32_t)slot>=m->states)return fail(r,RSM_FAULT_COUNTER,2,"STATE_SLOT",iid,op,u32(a+4));rise=*power&&!m->state[slot].edge;m->state[slot].edge=(uint8_t)*power;if(op==RSM_OP_CTU){t->v.counter.cu=(uint8_t)*power;if(rise){if(t->v.counter.acc==INT32_MAX){t->v.counter.acc=INT32_MIN;t->v.counter.ov=1;}else t->v.counter.acc++;}}else{t->v.counter.cd=(uint8_t)*power;if(rise){if(t->v.counter.acc==INT32_MIN){t->v.counter.acc=INT32_MAX;t->v.counter.un=1;}else t->v.counter.acc--;}}t->v.counter.dn=(rsm_bool_t)(t->v.counter.acc>=t->v.counter.pre);}
 else if(op==RSM_OP_RES){tag_t*t;NEED(1);if(!*power)return RSM_STATUS_OK;if(a[0]!=1||u32(a+4)>=m->tags)return fail(r,RSM_FAULT_EXECUTION,6,"RES_TAG",iid,op,u32(a+4));t=&m->tag[u32(a+4)];if(t->type==4){t->v.timer.acc=0;t->v.timer.en=t->v.timer.tt=t->v.timer.dn=0;}else if(t->type==5){t->v.counter.acc=0;t->v.counter.cu=t->v.counter.cd=t->v.counter.dn=t->v.counter.ov=t->v.counter.un=0;}else return fail(r,RSM_FAULT_EXECUTION,7,"RES_TYPE",iid,op,u32(a+4));}
 else if(op>=RSM_OP_EQ&&op<=RSM_OP_LE){NEED(2);if(operand(m,b,&y)||!numeric(&x)||!numeric(&y))return fail(r,RSM_FAULT_EXECUTION,8,"COMPARE_TYPE",iid,op,NONE);{double q=number(&x),w=number(&y);bool yes=op==RSM_OP_EQ?q==w:op==RSM_OP_NE?q!=w:op==RSM_OP_GT?q>w:op==RSM_OP_GE?q>=w:op==RSM_OP_LT?q<w:q<=w;*power=*power&&yes;}}
 else if(op==RSM_OP_CLR){NEED(1);if(*power){z.type=(rsm_data_type_t)m->tag[u32(a+4)].type;if(z.type==RSM_TYPE_BOOL)z.value.boolean=0;else if(z.type==RSM_TYPE_DINT)z.value.dint=0;else if(z.type==RSM_TYPE_REAL)z.value.real=0.0f;else return fail(r,RSM_FAULT_EXECUTION,9,"CLR_TYPE",iid,op,u32(a+4));if(destination(m,a,&z))return fail(r,RSM_FAULT_EXECUTION,10,"WRITE",iid,op,u32(a+4));}}
 else if(op==RSM_OP_MOV){NEED(2);if(*power){if(b[0]!=1||u32(b+4)>=m->tags)return fail(r,RSM_FAULT_EXECUTION,11,"DEST",iid,op,NONE);z.type=(rsm_data_type_t)m->tag[u32(b+4)].type;if(z.type==x.type)z=x;else if(z.type==RSM_TYPE_REAL&&x.type==RSM_TYPE_DINT)z.value.real=(float)x.value.dint;else if(z.type==RSM_TYPE_DINT&&x.type==RSM_TYPE_REAL&&isfinite(x.value.real)&&x.value.real<2147483648.0f&&x.value.real>=-2147483648.0f)z.value.dint=(int32_t)x.value.real;else return fail(r,RSM_FAULT_NUMERIC,1,"CONVERSION",iid,op,u32(b+4));if(destination(m,b,&z))return fail(r,RSM_FAULT_EXECUTION,12,"WRITE",iid,op,u32(b+4));}}
 else if(op>=RSM_OP_ADD&&op<=RSM_OP_DIV){NEED(3);if(!*power)return RSM_STATUS_OK;if(operand(m,b,&y)||!numeric(&x)||!numeric(&y)||d[0]!=1||u32(d+4)>=m->tags)return fail(r,RSM_FAULT_EXECUTION,13,"MATH_OPERAND",iid,op,NONE);z.type=(rsm_data_type_t)m->tag[u32(d+4)].type;if(z.type==RSM_TYPE_DINT&&x.type==RSM_TYPE_DINT&&y.type==RSM_TYPE_DINT){int64_t q;if(op==RSM_OP_DIV){if(y.value.dint==0)return fail(r,RSM_FAULT_NUMERIC,2,"DIV_ZERO",iid,op,u32(d+4));if(x.value.dint==INT32_MIN&&y.value.dint==-1)return fail(r,RSM_FAULT_NUMERIC,3,"OVERFLOW",iid,op,u32(d+4));q=x.value.dint/y.value.dint;}else if(op==RSM_OP_ADD)q=(int64_t)x.value.dint+y.value.dint;else if(op==RSM_OP_SUB)q=(int64_t)x.value.dint-y.value.dint;else q=(int64_t)x.value.dint*y.value.dint;if(q>INT32_MAX||q<INT32_MIN)return fail(r,RSM_FAULT_NUMERIC,3,"OVERFLOW",iid,op,u32(d+4));z.value.dint=(int32_t)q;}else if(z.type==RSM_TYPE_REAL){float q,w=(float)number(&y),v=(float)number(&x);if(op==RSM_OP_DIV&&w==0.0f)return fail(r,RSM_FAULT_NUMERIC,2,"DIV_ZERO",iid,op,u32(d+4));q=op==RSM_OP_ADD?v+w:op==RSM_OP_SUB?v-w:op==RSM_OP_MUL?v*w:v/w;if(!isfinite(q))return fail(r,RSM_FAULT_NUMERIC,3,"NON_FINITE",iid,op,u32(d+4));z.value.real=q;}else return fail(r,RSM_FAULT_EXECUTION,14,"MATH_TYPE",iid,op,u32(d+4));if(destination(m,d,&z))return fail(r,RSM_FAULT_EXECUTION,15,"WRITE",iid,op,u32(d+4));}
 else if(op==RSM_OP_NEG||op==RSM_OP_ABS){NEED(2);if(*power){if(b[0]!=1||u32(b+4)>=m->tags)return fail(r,RSM_FAULT_EXECUTION,16,"DEST",iid,op,NONE);z.type=(rsm_data_type_t)m->tag[u32(b+4)].type;if(z.type==RSM_TYPE_DINT&&x.type==RSM_TYPE_DINT){if(x.value.dint==INT32_MIN)return fail(r,RSM_FAULT_NUMERIC,3,"OVERFLOW",iid,op,u32(b+4));z.value.dint=op==RSM_OP_NEG?-x.value.dint:(x.value.dint<0?-x.value.dint:x.value.dint);}else if(z.type==RSM_TYPE_REAL&&numeric(&x)){float q=(float)number(&x);z.value.real=op==RSM_OP_NEG?-q:fabsf(q);}else return fail(r,RSM_FAULT_EXECUTION,17,"MATH_TYPE",iid,op,NONE);if(destination(m,b,&z))return fail(r,RSM_FAULT_EXECUTION,18,"WRITE",iid,op,u32(b+4));}}
 else { return fail(r,RSM_FAULT_EXECUTION,19,"UNSUPPORTED_OPCODE",iid,op,NONE); }
 m->diag.last_instruction_id=iid;
 return RSM_STATUS_OK;
#undef NEED
}
static void prescan(impl_t*m){uint32_t i;for(i=0;i<m->states;i++){m->state[i].edge=1;m->state[i].valid=0;}for(i=0;i<m->tags;i++){if(m->tag[i].type==4){m->tag[i].v.timer.en=m->tag[i].v.timer.tt=m->tag[i].v.timer.dn=0;}else if(m->tag[i].type==5){m->tag[i].v.counter.cu=m->tag[i].v.counter.cd=0;}}}
rsm_status_t rsm_runtime_set_mode(rsm_runtime_t*r,rsm_mode_t mode){if(!r||mode>RSM_MODE_FAULTED)return RSM_STATUS_INVALID_ARGUMENT;if((mode==RSM_MODE_RUN||mode==RSM_MODE_TEST)&&!r->impl)return RSM_STATUS_INVALID_STATE;if(r->mode==RSM_MODE_FAULTED&&mode!=RSM_MODE_PROGRAM)return RSM_STATUS_INVALID_STATE;if((mode==RSM_MODE_RUN||mode==RSM_MODE_TEST)&&(r->mode==RSM_MODE_PROGRAM)){prescan(r->impl);}if(mode==RSM_MODE_PROGRAM&&r->impl)prescan(r->impl);r->mode=mode;return RSM_STATUS_OK;}
rsm_mode_t rsm_runtime_get_mode(const rsm_runtime_t*r){return r?r->mode:RSM_MODE_FAULTED;}
rsm_status_t rsm_runtime_scan(rsm_runtime_t*r){impl_t*m;size_t o=0;uint32_t index=0,rung=0;bool power=true;uint64_t start,end;if(!r||!r->impl)return RSM_STATUS_INVALID_ARGUMENT;if(r->mode!=RSM_MODE_RUN&&r->mode!=RSM_MODE_TEST)return r->mode==RSM_MODE_FAULTED?RSM_STATUS_FAULTED:RSM_STATUS_INVALID_STATE;m=r->impl;start=now(r);m->diag.last_scan_start_us=start;
/* Inputs are captured once. Endpoint IDs intentionally equal dense tag IDs. */
{uint32_t i;for(i=0;i<m->tags;i++)if(m->tag[i].storage==1&&r->hal.read_input){rsm_value_t v;rsm_status_t s;value(m,i,&v);s=r->hal.read_input(r->hal_context,i,&v);if(s)return fail(r,RSM_FAULT_HAL,1,"INPUT",NONE,0,i);if(v.type!=(rsm_data_type_t)m->tag[i].type)return fail(r,RSM_FAULT_HAL,2,"INPUT_TYPE",NONE,0,i);if(v.type==RSM_TYPE_BOOL)m->tag[i].v.b=v.value.boolean?1u:0u;else if(v.type==RSM_TYPE_DINT)m->tag[i].v.d=v.value.dint;else m->tag[i].v.f=v.value.real;}}
while(o<m->code_size){uint8_t ac;if(rung<m->rungs&&index==u32(m->rung_data+(size_t)rung*12u+4)){power=true;rung++;}ac=m->code[o+1];if(execute(r,m->code+o,&power,start))return RSM_STATUS_FAULTED;o+=12u+(size_t)ac*8u;index++;}
if(r->mode==RSM_MODE_RUN&&r->hal.write_output){uint32_t i;for(i=0;i<m->tags;i++)if(m->tag[i].storage==2){rsm_value_t v;if(value(m,i,&v)||r->hal.write_output(r->hal_context,i,&v))return fail(r,RSM_FAULT_HAL,3,"OUTPUT",NONE,0,i);}}
end=now(r);m->diag.last_scan_duration_us=end-start;m->diag.scan_count++;if(m->diag.last_scan_duration_us>m->diag.max_scan_duration_us)m->diag.max_scan_duration_us=m->diag.last_scan_duration_us;m->diag.average_scan_duration_us+=(m->diag.last_scan_duration_us-m->diag.average_scan_duration_us)/m->diag.scan_count;if(r->hal.kick_watchdog&&r->hal.kick_watchdog(r->hal_context))return fail(r,RSM_FAULT_WATCHDOG,1,"WATCHDOG",NONE,0,NONE);return RSM_STATUS_OK;}
rsm_status_t rsm_runtime_snapshot(const rsm_runtime_t*r,rsm_snapshot_writer_t*w){impl_t*m;uint32_t i;if(!r||!r->impl||!w||!w->value)return RSM_STATUS_INVALID_ARGUMENT;m=r->impl;for(i=0;i<m->tags;i++)if(m->tag[i].type<=3){rsm_value_t logical,effective;logical.type=(rsm_data_type_t)m->tag[i].type;if(logical.type==RSM_TYPE_BOOL)logical.value.boolean=m->tag[i].v.b;else if(logical.type==RSM_TYPE_DINT)logical.value.dint=m->tag[i].v.d;else logical.value.real=m->tag[i].v.f;effective=logical;if(m->force[i].enabled)effective=m->force[i].value;{rsm_status_t s=w->value(w->context,i,&logical,&effective,m->force[i].enabled);if(s)return s;}}return RSM_STATUS_OK;}
rsm_status_t rsm_runtime_get_diagnostics(const rsm_runtime_t*r,rsm_runtime_diagnostics_t*d){if(!r||!r->impl||!d)return RSM_STATUS_INVALID_ARGUMENT;*d=((impl_t*)r->impl)->diag;return RSM_STATUS_OK;}
const rsm_fault_t *rsm_runtime_last_fault(const rsm_runtime_t*r){return (r&&r->impl)?&((impl_t*)r->impl)->fault:NULL;}
