#include "rsmicro/rsm_runtime.h"
#include "rsm_conformance_fixtures.h"
#include <stdio.h>
#include <string.h>

#define CAP 512u
#define OP_UNLOAD 11u
#define OP_LOAD 12u
#define OP_READ 13u

static uint64_t fixture_time_us;
static unsigned snapshot_values, snapshot_members, output_writes;
typedef struct { uint32_t tag; rsm_value_t logical,effective; rsm_bool_t forced; } force_seen_t;
typedef struct { uint32_t slot; uint8_t edge,valid; uint64_t time; } state_seen_t;
typedef struct { uint32_t rung; rsm_bool_t power; } rung_seen_t;
typedef struct { force_seen_t force[CAP]; size_t forces; state_seen_t state[CAP]; size_t states; rung_seen_t rung[CAP]; size_t rungs; } observed_t;
static observed_t observed;

static uint64_t fixture_clock(void *context) { (void)context; return fixture_time_us; }
static rsm_status_t fixture_output(void *context, uint32_t endpoint, const rsm_value_t *value) { (void)context; (void)endpoint; (void)value; ++output_writes; return RSM_STATUS_OK; }
static rsm_status_t snapshot_value(void *context, rsm_tag_id_t tag, const rsm_value_t *logical, const rsm_value_t *effective, rsm_bool_t forced) { force_seen_t *x; (void)context; ++snapshot_values; if(observed.forces>=CAP)return RSM_STATUS_OK; x=&observed.force[observed.forces++];x->tag=tag;x->logical=*logical;x->effective=*effective;x->forced=forced;return RSM_STATUS_OK; }
static rsm_status_t snapshot_member(void *context, rsm_tag_id_t tag, rsm_member_id_t member, const rsm_value_t *value) { (void)context;(void)tag;(void)member;(void)value;++snapshot_members;return RSM_STATUS_OK; }
static rsm_status_t snapshot_state(void *context, uint8_t mode, const rsm_runtime_diagnostics_t *diag, const rsm_fault_t *fault, uint32_t slot, uint8_t edge, uint8_t valid, uint64_t time) { state_seen_t *x;(void)context;(void)mode;(void)diag;(void)fault;if(slot==UINT32_MAX||observed.states>=CAP)return RSM_STATUS_OK;x=&observed.state[observed.states++];x->slot=slot;x->edge=edge;x->valid=valid;x->time=time;return RSM_STATUS_OK; }
static rsm_status_t snapshot_rung(void *context, uint32_t rung, rsm_bool_t power) { rung_seen_t *x;(void)context;if(observed.rungs>=CAP)return RSM_STATUS_OK;x=&observed.rung[observed.rungs++];x->rung=rung;x->power=power;return RSM_STATUS_OK; }

static int same_value(const rsm_value_t *actual, const rsm_value_t *expected) { if(actual->type!=expected->type)return 0; if(actual->type==RSM_TYPE_BOOL)return actual->value.boolean==expected->value.boolean; if(actual->type==RSM_TYPE_DINT)return actual->value.dint==expected->value.dint; return actual->value.real==expected->value.real; }
static int assert_values(const rsm_runtime_t *runtime,const rsm_conformance_step_t *step) { size_t i; for(i=0;i<step->assertion_count;i++){const rsm_conformance_assertion_t*a=&step->assertions[i];rsm_value_t actual; rsm_status_t s=a->member?rsm_runtime_read_member(runtime,a->tag,a->member,&actual):rsm_runtime_read_tag(runtime,a->tag,&actual);if(s||!same_value(&actual,&a->value)){fprintf(stderr,"value assertion tag %u member %u status %d\n",a->tag,a->member,(int)s);return 0;}}return 1; }
static int assert_state(const rsm_conformance_step_t *step) { size_t i,j; for(i=0;i<step->force_count;i++){const rsm_conformance_force_assertion_t*a=&step->forces[i];for(j=0;j<observed.forces&&observed.force[j].tag!=a->tag;j++);if(j==observed.forces||observed.force[j].forced!=a->forced||!same_value(&observed.force[j].logical,&a->logical)||!same_value(&observed.force[j].effective,&a->effective)){fprintf(stderr,"force/logical/effective assertion tag %u\n",a->tag);return 0;}}for(i=0;i<step->instruction_state_count;i++){const rsm_conformance_instruction_state_assertion_t*a=&step->instruction_states[i];for(j=0;j<observed.states&&observed.state[j].slot!=a->slot;j++);if(j==observed.states||observed.state[j].edge!=a->edge||observed.state[j].valid!=a->valid||observed.state[j].time!=a->time_us){fprintf(stderr,"instruction state assertion slot %u\n",a->slot);return 0;}}for(i=0;i<step->rung_power_count;i++){const rsm_conformance_rung_power_assertion_t*a=&step->rung_powers[i];for(j=0;j<observed.rungs&&observed.rung[j].rung!=a->rung;j++);if(j==observed.rungs||observed.rung[j].power!=a->power){fprintf(stderr,"rung power assertion rung %u\n",a->rung);return 0;}}return 1; }
static int assert_trace(const rsm_runtime_t*r,const rsm_conformance_step_t*step){rsm_runtime_write_trace_entry_t got[RSM_RUNTIME_WRITE_TRACE_CAPACITY];size_t n=0,i;if(!step->write_trace_declared)return 1;if(rsm_runtime_get_write_trace(r,got,RSM_RUNTIME_WRITE_TRACE_CAPACITY,&n)||n!=step->write_count){fprintf(stderr,"write trace count %lu expected %lu\n",(unsigned long)n,(unsigned long)step->write_count);return 0;}for(i=0;i<n;i++)if(got[i].tag!=step->writes[i].tag||!same_value(&got[i].value,&step->writes[i].value)){fprintf(stderr,"write trace mismatch at %lu\n",(unsigned long)i);return 0;}return 1;}
static rsm_status_t operate(rsm_runtime_t *r,const rsm_conformance_step_t *s,const rsm_conformance_fixture_t *f) { rsm_value_t value; switch(s->operation){case 1:return rsm_runtime_prescan(r);case 2:return rsm_runtime_postscan(r);case 3:return rsm_runtime_scan(r);case 4:return rsm_runtime_write_tag(r,s->tag,&s->value);case 5:return rsm_runtime_set_mode(r,RSM_MODE_RUN);case 6:return rsm_runtime_set_mode(r,RSM_MODE_PROGRAM);case 7:return rsm_runtime_set_mode(r,RSM_MODE_TEST);case 8:return rsm_runtime_force_tag(r,s->tag,&s->value);case 9:return rsm_runtime_clear_force(r,s->tag);case 10:return rsm_runtime_clear_all_forces(r);case OP_UNLOAD:return rsm_runtime_unload_program(r);case OP_LOAD:return rsm_runtime_load_image(r,f->image,f->image_size);case OP_READ:return rsm_runtime_read_tag(r,s->tag,&value);default:return RSM_STATUS_INVALID_ARGUMENT;} }
static int assert_unloaded(const rsm_runtime_t *r) { rsm_value_t value; rsm_runtime_diagnostics_t diag; rsm_snapshot_writer_t writer; size_t trace=0; memset(&writer,0,sizeof writer);writer.value=snapshot_value; return rsm_runtime_read_tag(r,0u,&value)==RSM_STATUS_INVALID_STATE&&rsm_runtime_scan((rsm_runtime_t *)r)==RSM_STATUS_INVALID_STATE&&rsm_runtime_snapshot(r,&writer)==RSM_STATUS_INVALID_STATE&&rsm_runtime_get_diagnostics(r,&diag)==RSM_STATUS_INVALID_STATE&&rsm_runtime_get_write_trace(r,NULL,0u,&trace)==RSM_STATUS_INVALID_STATE; }
static int observe_active(const rsm_runtime_t *r,const rsm_conformance_step_t *s) { rsm_runtime_diagnostics_t before,after; rsm_snapshot_writer_t w; const rsm_fault_t *fault; snapshot_values=snapshot_members=0;memset(&observed,0,sizeof observed);memset(&w,0,sizeof w);w.value=snapshot_value;w.member=snapshot_member;w.state=snapshot_state;w.rung_power=snapshot_rung;if(rsm_runtime_get_diagnostics(r,&before)||rsm_runtime_snapshot(r,&w)||rsm_runtime_get_diagnostics(r,&after)||before.scan_count!=after.scan_count||!assert_state(s))return 0;if(s->expected_scan_count!=UINT64_MAX&&after.scan_count!=s->expected_scan_count)return 0;fault=rsm_runtime_last_fault(r);if(s->expected_fault_category>=0&&(!fault||(int)fault->category!=s->expected_fault_category||fault->code!=s->expected_fault_code))return 0;if(!snapshot_values&&!snapshot_members)return 0;return 1; }

int main(void) { size_t fi; unsigned passed=0; for(fi=0;fi<rsm_conformance_fixture_count;fi++){const rsm_conformance_fixture_t*f=&rsm_conformance_fixtures[fi];rsm_runtime_t r,peer;rsm_hal_t h;unsigned char arena[65536],peer_arena[65536];size_t si; rsm_value_t peer_before,peer_after;int peer_observed=0;memset(&h,0,sizeof h);h.monotonic_time_us=fixture_clock;h.write_output=fixture_output;fixture_time_us=0;output_writes=0;if(rsm_runtime_init(&r,arena,sizeof arena,&h,NULL)||rsm_runtime_init(&peer,peer_arena,sizeof peer_arena,&h,NULL)||rsm_runtime_load_image(&r,f->image,f->image_size)||rsm_runtime_load_image(&peer,f->image,f->image_size)){fprintf(stderr,"%s: image did not load\n",f->id);return 1;}if(rsm_runtime_read_tag(&peer,0u,&peer_before)==RSM_STATUS_OK)peer_observed=1;for(si=0;si<f->step_count;si++){const rsm_conformance_step_t*s=&f->steps[si];rsm_status_t status;fixture_time_us=s->time_us;if(r.impl&&rsm_runtime_clear_write_trace(&r)){fprintf(stderr,"%s trace clear\n",f->id);return 1;}status=operate(&r,s,f);if((int)status!=s->expected_status){fprintf(stderr,"%s step %lu status %d expected %d\n",f->id,(unsigned long)si,(int)status,s->expected_status);return 1;}if(s->expected_mode>=0&&(int)rsm_runtime_get_mode(&r)!=s->expected_mode){fprintf(stderr,"%s step %lu mode mismatch\n",f->id,(unsigned long)si);return 1;}if(!r.impl){if(!assert_unloaded(&r)){fprintf(stderr,"%s step %lu unloaded API contract failed\n",f->id,(unsigned long)si);return 1;}if(s->operation==OP_UNLOAD&&peer_observed){if(rsm_runtime_read_tag(&peer,0u,&peer_after)||!same_value(&peer_before,&peer_after)){fprintf(stderr,"%s unload changed peer runtime\n",f->id);return 1;}}continue;}if(!assert_values(&r,s)||!assert_trace(&r,s)||!observe_active(&r,s)){fprintf(stderr,"%s step %lu assertion mismatch\n",f->id,(unsigned long)si);return 1;}if(s->expected_output_writes>=0&&output_writes!=(unsigned)s->expected_output_writes){fprintf(stderr,"%s step %lu output writes mismatch\n",f->id,(unsigned long)si);return 1;}if(s->operation==OP_UNLOAD&&peer_observed){if(rsm_runtime_read_tag(&peer,0u,&peer_after)||!same_value(&peer_before,&peer_after)){fprintf(stderr,"%s unload changed peer runtime\n",f->id);return 1;}}}rsm_runtime_deinit(&r);rsm_runtime_deinit(&peer);passed++;}printf("semantic conformance fixtures: %u executed\n",passed);return 0;}
