from enum import IntEnum, IntFlag
MAGIC=b"RSML"; FRAME_VERSION=1; PROTOCOL_MAJOR=1; PROTOCOL_MINOR=0; SCHEMA_VERSION=1
HEADER_SIZE=24; TRAILER_SIZE=4; MIN_FRAME_SIZE=28; MAX_FRAME_SIZE=1_048_576; MAX_PAYLOAD_SIZE=MAX_FRAME_SIZE-MIN_FRAME_SIZE
class MessageType(IntEnum):
 HELLO=1; HELLO_RESPONSE=2; CAPABILITIES_REQUEST=3; CAPABILITIES_RESPONSE=4; HEARTBEAT=5; HEARTBEAT_RESPONSE=6
 GET_PROGRAM_INFO=16; PROGRAM_INFO=17; PROGRAM_BEGIN=18; PROGRAM_CHUNK=19; PROGRAM_VALIDATE=20; PROGRAM_VALIDATION_RESULT=21; PROGRAM_ACTIVATE=22; PROGRAM_ACTIVATION_RESULT=23; PROGRAM_ABORT=24; PROGRAM_ROLLBACK=25
 GET_MODE=32; MODE_STATUS=33; SET_MODE=34; GET_TAG_MANIFEST=48; TAG_MANIFEST_BEGIN=49; TAG_MANIFEST_CHUNK=50; TAG_MANIFEST_END=51; READ_TAG=52; READ_TAG_RESPONSE=53; WRITE_TAG=54; SET_SIM_INPUT=55
 FORCE_TAG=64; CLEAR_FORCE=65; CLEAR_ALL_FORCES=66; FORCE_STATUS=67; SUBSCRIBE_TAGS=80; SUBSCRIPTION_STATUS=81; UNSUBSCRIBE_TAGS=82; TAG_UPDATE=83
 GET_SNAPSHOT=96; SNAPSHOT_BEGIN=97; SNAPSHOT_CHUNK=98; SNAPSHOT_END=99; GET_DIAGNOSTICS=100; DIAGNOSTICS_RESPONSE=101; FAULT_EVENT=102; ACK=126; ERROR=127
class FrameFlags(IntFlag): OPTIONAL_MESSAGE=1
